import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./header";
import NavMenu from "./NavMenu";
import "./globals.css";
import AuthProvider from './AuthProvider'
import { Toaster } from "react-hot-toast"
import CartContext from "./CartContext";
import { Car } from "lucide-react";
import { Footer } from "@/components/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <AuthProvider>
      <CartContext>
       
          <html lang="en">
            <body>
              <div className="header">
                <Header/>
              </div>
              <div className="navmenu">
                <NavMenu/>
              </div>
              <div className="main">
                {children}
              </div>
              <Toaster />
              <Footer />
            </body>
          </html>
        
      </CartContext>
    </AuthProvider>
  );
}
