import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/header/header";
import NavMenu from "@/components/navmenu/NavMenu";
import "./globals.css";
import AuthProvider from '@/components/context/AuthProvider'
import { Toaster } from "react-hot-toast"
import CartContext from "@/components/context/CartContext";
import { Footer } from "@/components/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <AuthProvider>
      <CartContext>
       
          <html lang="en">
            <body>
              <div className="header">
                <Header/>
              </div>
              <div className="navmenu">
                <NavMenu/>
              </div>
              <div className="main">
                {children}
              </div>
              <Toaster />
              <div id='footer'>
                <Footer/>
              </div>
                
            </body>
          </html>
        
      </CartContext>
    </AuthProvider>
  );
}
